# Generated by Django 5.2.8 on 2025-11-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_actor_actor_name_en_actor_actor_name_ru_actor_bio_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
