# Generated by Django 5.2.8 on 2025-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_country_country_name_en_country_country_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielanguages',
            name='language_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
